alias: Oref - OK to PRE_ALERT - Snapshot + Lights ON (Jerusalem South)
triggers:
  - entity_id: sensor.oref_alert
    from: ok
    to: pre_alert
    trigger: state
conditions:
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect_4
    state: "off"
  - condition: template
    value_template: |
      {{ 'ירושלים - דרום' in
         (state_attr('sensor.oref_alert', 'record').data | default('')) }}
actions:
  - data:
      scene_id: oref_pre_alert_snapshot
      snapshot_entities:
        - switch.sonoff_100057456d_1
        - switch.sonoff_100057456d_2
        - light.interupteur_salon
    action: scene.create
  - target:
      entity_id:
        - switch.sonoff_100057456d_1
        - switch.sonoff_100057456d_2
    action: switch.turn_on
  - target:
      entity_id: light.interupteur_salon
    action: light.turn_on
mode: single
