alias: Oref - OK to PRE_ALERT - Lights ON (Jerusalem South - Shabbat)
triggers:
  - entity_id: sensor.oref_alert
    from: ok
    to: pre_alert
    trigger: state
conditions:
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect_4
    state: "on"
  - condition: template
    value_template: |
      {{ 'ירושלים - דרום' in
         (state_attr('sensor.oref_alert', 'record').data | default('')) }}
actions:
  - target:
      entity_id:
        - switch.sonoff_100057456d_1
        - switch.sonoff_100057456d_2
        - light.interupteur_salon
    action: homeassistant.turn_on
mode: single
